/**
 * MDP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Cost from './model/Cost';
import Direction from './model/Direction';
import ErrorContext from './model/ErrorContext';
import ErrorType from './model/ErrorType';
import ImagePredictionResponse from './model/ImagePredictionResponse';
import Location from './model/Location';
import Message from './model/Message';
import MiscInstruction from './model/MiscInstruction';
import Move from './model/Move';
import Path from './model/Path';
import PathfindingPoint from './model/PathfindingPoint';
import PathfindingRequest from './model/PathfindingRequest';
import PathfindingRequestObstacle from './model/PathfindingRequestObstacle';
import PathfindingRequestRobot from './model/PathfindingRequestRobot';
import PathfindingResponse from './model/PathfindingResponse';
import PathfindingResponseMoveInstruction from './model/PathfindingResponseMoveInstruction';
import PathfindingResponseSegment from './model/PathfindingResponseSegment';
import PathfindingResponseSegmentInstructionsInner from './model/PathfindingResponseSegmentInstructionsInner';
import PathfindingVector from './model/PathfindingVector';
import TurnInstruction from './model/TurnInstruction';
import ValidationErrorModel from './model/ValidationErrorModel';
import ImageRecognitionApi from './api/ImageRecognitionApi';
import PathfindingApi from './api/PathfindingApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var MdpApi = require('index'); // See note below*.
* var xxxSvc = new MdpApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new MdpApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new MdpApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new MdpApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Cost model constructor.
     * @property {module:model/Cost}
     */
    Cost,

    /**
     * The Direction model constructor.
     * @property {module:model/Direction}
     */
    Direction,

    /**
     * The ErrorContext model constructor.
     * @property {module:model/ErrorContext}
     */
    ErrorContext,

    /**
     * The ErrorType model constructor.
     * @property {module:model/ErrorType}
     */
    ErrorType,

    /**
     * The ImagePredictionResponse model constructor.
     * @property {module:model/ImagePredictionResponse}
     */
    ImagePredictionResponse,

    /**
     * The Location model constructor.
     * @property {module:model/Location}
     */
    Location,

    /**
     * The Message model constructor.
     * @property {module:model/Message}
     */
    Message,

    /**
     * The MiscInstruction model constructor.
     * @property {module:model/MiscInstruction}
     */
    MiscInstruction,

    /**
     * The Move model constructor.
     * @property {module:model/Move}
     */
    Move,

    /**
     * The Path model constructor.
     * @property {module:model/Path}
     */
    Path,

    /**
     * The PathfindingPoint model constructor.
     * @property {module:model/PathfindingPoint}
     */
    PathfindingPoint,

    /**
     * The PathfindingRequest model constructor.
     * @property {module:model/PathfindingRequest}
     */
    PathfindingRequest,

    /**
     * The PathfindingRequestObstacle model constructor.
     * @property {module:model/PathfindingRequestObstacle}
     */
    PathfindingRequestObstacle,

    /**
     * The PathfindingRequestRobot model constructor.
     * @property {module:model/PathfindingRequestRobot}
     */
    PathfindingRequestRobot,

    /**
     * The PathfindingResponse model constructor.
     * @property {module:model/PathfindingResponse}
     */
    PathfindingResponse,

    /**
     * The PathfindingResponseMoveInstruction model constructor.
     * @property {module:model/PathfindingResponseMoveInstruction}
     */
    PathfindingResponseMoveInstruction,

    /**
     * The PathfindingResponseSegment model constructor.
     * @property {module:model/PathfindingResponseSegment}
     */
    PathfindingResponseSegment,

    /**
     * The PathfindingResponseSegmentInstructionsInner model constructor.
     * @property {module:model/PathfindingResponseSegmentInstructionsInner}
     */
    PathfindingResponseSegmentInstructionsInner,

    /**
     * The PathfindingVector model constructor.
     * @property {module:model/PathfindingVector}
     */
    PathfindingVector,

    /**
     * The TurnInstruction model constructor.
     * @property {module:model/TurnInstruction}
     */
    TurnInstruction,

    /**
     * The ValidationErrorModel model constructor.
     * @property {module:model/ValidationErrorModel}
     */
    ValidationErrorModel,

    /**
    * The ImageRecognitionApi service constructor.
    * @property {module:api/ImageRecognitionApi}
    */
    ImageRecognitionApi,

    /**
    * The PathfindingApi service constructor.
    * @property {module:api/PathfindingApi}
    */
    PathfindingApi
};
