# coding: utf-8

"""
    MDP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.pathfinding_request import PathfindingRequest

class TestPathfindingRequest(unittest.TestCase):
    """PathfindingRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PathfindingRequest:
        """Test PathfindingRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PathfindingRequest`
        """
        model = PathfindingRequest()
        if include_optional:
            return PathfindingRequest(
                obstacles = [
                    openapi_client.models.pathfinding_request_obstacle.PathfindingRequestObstacle(
                        direction = null, 
                        image_id = 1.0, 
                        north_east = null, 
                        south_west = null, )
                    ],
                robot = openapi_client.models.pathfinding_request_robot.PathfindingRequestRobot(
                    direction = null, 
                    north_east = null, 
                    south_west = null, ),
                verbose = True
            )
        else:
            return PathfindingRequest(
                obstacles = [
                    openapi_client.models.pathfinding_request_obstacle.PathfindingRequestObstacle(
                        direction = null, 
                        image_id = 1.0, 
                        north_east = null, 
                        south_west = null, )
                    ],
                robot = openapi_client.models.pathfinding_request_robot.PathfindingRequestRobot(
                    direction = null, 
                    north_east = null, 
                    south_west = null, ),
        )
        """

    def testPathfindingRequest(self):
        """Test PathfindingRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
