# coding: utf-8

"""
    MDP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field
from typing import Any, ClassVar, Dict, List
from openapi_client.models.direction import Direction
from openapi_client.models.pathfinding_point import PathfindingPoint
from typing import Optional, Set
from typing_extensions import Self

class PathfindingRequestRobot(BaseModel):
    """
    PathfindingRequestRobot
    """ # noqa: E501
    direction: Direction = Field(description="The direction of the robot.")
    north_east: PathfindingPoint = Field(description="The north-east corner of the robot.")
    south_west: PathfindingPoint = Field(description="The south-west corner of the robot.")
    __properties: ClassVar[List[str]] = ["direction", "north_east", "south_west"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PathfindingRequestRobot from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of north_east
        if self.north_east:
            _dict['north_east'] = self.north_east.to_dict()
        # override the default output from pydantic by calling `to_dict()` of south_west
        if self.south_west:
            _dict['south_west'] = self.south_west.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PathfindingRequestRobot from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "direction": obj.get("direction"),
            "north_east": PathfindingPoint.from_dict(obj["north_east"]) if obj.get("north_east") is not None else None,
            "south_west": PathfindingPoint.from_dict(obj["south_west"]) if obj.get("south_west") is not None else None
        })
        return _obj


