/**
 * MDP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class MiscInstruction.
* @enum {}
* @readonly
*/
export default class MiscInstruction {
    
        /**
         * value: "CAPTURE_IMAGE"
         * @const
         */
        "CAPTURE_IMAGE" = "CAPTURE_IMAGE";

    
        /**
         * value: "RESET_GYROSCOPE"
         * @const
         */
        "RESET_GYROSCOPE" = "RESET_GYROSCOPE";

    

    /**
    * Returns a <code>MiscInstruction</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/MiscInstruction} The enum <code>MiscInstruction</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

