/**
 * MDP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Direction from './Direction';

/**
 * The PathfindingVector model module.
 * @module model/PathfindingVector
 * @version 1.0.0
 */
class PathfindingVector {
    /**
     * Constructs a new <code>PathfindingVector</code>.
     * @alias module:model/PathfindingVector
     * @param direction {module:model/Direction} The direction
     * @param x {Number} 
     * @param y {Number} 
     */
    constructor(direction, x, y) { 
        
        PathfindingVector.initialize(this, direction, x, y);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, direction, x, y) { 
        obj['direction'] = direction;
        obj['x'] = x;
        obj['y'] = y;
    }

    /**
     * Constructs a <code>PathfindingVector</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PathfindingVector} obj Optional instance to populate.
     * @return {module:model/PathfindingVector} The populated <code>PathfindingVector</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PathfindingVector();

            if (data.hasOwnProperty('direction')) {
                obj['direction'] = ApiClient.convertToType(data['direction'], Direction);
            }
            if (data.hasOwnProperty('x')) {
                obj['x'] = ApiClient.convertToType(data['x'], 'Number');
            }
            if (data.hasOwnProperty('y')) {
                obj['y'] = ApiClient.convertToType(data['y'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PathfindingVector</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PathfindingVector</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PathfindingVector.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

PathfindingVector.RequiredProperties = ["direction", "x", "y"];

/**
 * The direction
 * @member {module:model/Direction} direction
 */
PathfindingVector.prototype['direction'] = undefined;

/**
 * @member {Number} x
 */
PathfindingVector.prototype['x'] = undefined;

/**
 * @member {Number} y
 */
PathfindingVector.prototype['y'] = undefined;






export default PathfindingVector;

