/**
 * MDP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MdpApi);
  }
}(this, function(expect, MdpApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MdpApi.ValidationErrorModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ValidationErrorModel', function() {
    it('should create an instance of ValidationErrorModel', function() {
      // uncomment below and update the code to test ValidationErrorModel
      //var instance = new MdpApi.ValidationErrorModel();
      //expect(instance).to.be.a(MdpApi.ValidationErrorModel);
    });

    it('should have the property ctx (base name: "ctx")', function() {
      // uncomment below and update the code to test the property ctx
      //var instance = new MdpApi.ValidationErrorModel();
      //expect(instance).to.be();
    });

    it('should have the property loc (base name: "loc")', function() {
      // uncomment below and update the code to test the property loc
      //var instance = new MdpApi.ValidationErrorModel();
      //expect(instance).to.be();
    });

    it('should have the property msg (base name: "msg")', function() {
      // uncomment below and update the code to test the property msg
      //var instance = new MdpApi.ValidationErrorModel();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type_")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new MdpApi.ValidationErrorModel();
      //expect(instance).to.be();
    });

  });

}));
