/**
 * MDP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class Direction.
* @enum {}
* @readonly
*/
export default class Direction {
    
        /**
         * value: "NORTH"
         * @const
         */
        "NORTH" = "NORTH";

    
        /**
         * value: "EAST"
         * @const
         */
        "EAST" = "EAST";

    
        /**
         * value: "SOUTH"
         * @const
         */
        "SOUTH" = "SOUTH";

    
        /**
         * value: "WEST"
         * @const
         */
        "WEST" = "WEST";

    

    /**
    * Returns a <code>Direction</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/Direction} The enum <code>Direction</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

