/**
 * MDP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Move from './Move';

/**
 * The PathfindingResponseMoveInstruction model module.
 * @module model/PathfindingResponseMoveInstruction
 * @version 1.0.0
 */
class PathfindingResponseMoveInstruction {
    /**
     * Constructs a new <code>PathfindingResponseMoveInstruction</code>.
     * @alias module:model/PathfindingResponseMoveInstruction
     * @param amount {Number} The amount to move the robot in centimetres.
     * @param move {module:model/Move} 
     */
    constructor(amount, move) { 
        
        PathfindingResponseMoveInstruction.initialize(this, amount, move);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, amount, move) { 
        obj['amount'] = amount;
        obj['move'] = move;
    }

    /**
     * Constructs a <code>PathfindingResponseMoveInstruction</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PathfindingResponseMoveInstruction} obj Optional instance to populate.
     * @return {module:model/PathfindingResponseMoveInstruction} The populated <code>PathfindingResponseMoveInstruction</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PathfindingResponseMoveInstruction();

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('move')) {
                obj['move'] = Move.constructFromObject(data['move']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PathfindingResponseMoveInstruction</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PathfindingResponseMoveInstruction</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PathfindingResponseMoveInstruction.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

PathfindingResponseMoveInstruction.RequiredProperties = ["amount", "move"];

/**
 * The amount to move the robot in centimetres.
 * @member {Number} amount
 */
PathfindingResponseMoveInstruction.prototype['amount'] = undefined;

/**
 * @member {module:model/Move} move
 */
PathfindingResponseMoveInstruction.prototype['move'] = undefined;






export default PathfindingResponseMoveInstruction;

