name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Test Android Compile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        java-version: 1.8
    - name: Make Gradle executable
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
  publish:
    name: Generate APK
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: 1.8
      - name: Make Gradle executable
        run: chmod +x gradlew
      - name: Save debug keystore
        run: echo $DEBUG_KEYSTORE | base64 -d > debug.keystore
        env:
          DEBUG_KEYSTORE: ${{ secrets.DEBUG_KEYSTORE }}
      - name: Generate Debug APK File
        run: ./gradlew assembleDebug -Pandroid.injected.signing.store.file=$(pwd)/debug.keystore -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD -Pandroid.injected.signing.key.alias=$KEY_ALIAS -Pandroid.injected.signing.key.password=$KEY_PASSWORD
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      - name: Generate Release APK File
        run: ./gradlew assembleRelease -Pandroid.injected.signing.store.file=$(pwd)/debug.keystore -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD -Pandroid.injected.signing.key.alias=$KEY_ALIAS -Pandroid.injected.signing.key.password=$KEY_PASSWORD
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      - name: Uploading Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug
      - name: Uploading Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release
  device-test:
    runs-on: macos-latest
    name: Android Device Test Runner
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Checkout all submodules
      run: git submodule update --init --recursive
    - name: Make Gradle executable
      run: chmod +x gradlew
    - name: List Available Android Devices
      run: $ANDROID_HOME/tools/bin/avdmanager list
    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 28
        target: google_apis
        profile: 'pixel_xl'
        arch: x86_64
        script: ./gradlew connectedAndroidTest
