# coding: utf-8

"""
    MDP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.image_recognition_api import ImageRecognitionApi


class TestImageRecognitionApi(unittest.TestCase):
    """ImageRecognitionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ImageRecognitionApi()

    def tearDown(self) -> None:
        pass

    def test_image_prediction_task1_post(self) -> None:
        """Test case for image_prediction_task1_post

        """
        pass

    def test_image_prediction_task2_post(self) -> None:
        """Test case for image_prediction_task2_post

        """
        pass

    def test_image_stitch_post(self) -> None:
        """Test case for image_stitch_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
