# coding: utf-8

"""
    MDP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.pathfinding_api import PathfindingApi


class TestPathfindingApi(unittest.TestCase):
    """PathfindingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PathfindingApi()

    def tearDown(self) -> None:
        pass

    def test_pathfinding_post(self) -> None:
        """Test case for pathfinding_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
