# coding: utf-8

"""
    MDP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.pathfinding_response_move_instruction import PathfindingResponseMoveInstruction

class TestPathfindingResponseMoveInstruction(unittest.TestCase):
    """PathfindingResponseMoveInstruction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PathfindingResponseMoveInstruction:
        """Test PathfindingResponseMoveInstruction
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PathfindingResponseMoveInstruction`
        """
        model = PathfindingResponseMoveInstruction()
        if include_optional:
            return PathfindingResponseMoveInstruction(
                amount = 1.0,
                move = 'FORWARD'
            )
        else:
            return PathfindingResponseMoveInstruction(
                amount = 1.0,
                move = 'FORWARD',
        )
        """

    def testPathfindingResponseMoveInstruction(self):
        """Test PathfindingResponseMoveInstruction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
