# coding: utf-8

"""
    MDP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.move import Move

class TestMove(unittest.TestCase):
    """Move unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMove(self):
        """Test Move"""
        # inst = Move()

if __name__ == '__main__':
    unittest.main()
