# coding: utf-8

"""
    MDP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.pathfinding_response import PathfindingResponse

class TestPathfindingResponse(unittest.TestCase):
    """PathfindingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PathfindingResponse:
        """Test PathfindingResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PathfindingResponse`
        """
        model = PathfindingResponse()
        if include_optional:
            return PathfindingResponse(
                segments = [
                    openapi_client.models.pathfinding_response_segment.PathfindingResponseSegment(
                        cost = null, 
                        image_id = 56, 
                        instructions = [
                            null
                            ], 
                        path = null, )
                    ]
            )
        else:
            return PathfindingResponse(
                segments = [
                    openapi_client.models.pathfinding_response_segment.PathfindingResponseSegment(
                        cost = null, 
                        image_id = 56, 
                        instructions = [
                            null
                            ], 
                        path = null, )
                    ],
        )
        """

    def testPathfindingResponse(self):
        """Test PathfindingResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
