# coding: utf-8

"""
    MDP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.pathfinding_request_obstacle import PathfindingRequestObstacle

class TestPathfindingRequestObstacle(unittest.TestCase):
    """PathfindingRequestObstacle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PathfindingRequestObstacle:
        """Test PathfindingRequestObstacle
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PathfindingRequestObstacle`
        """
        model = PathfindingRequestObstacle()
        if include_optional:
            return PathfindingRequestObstacle(
                direction = 'NORTH',
                image_id = 1.0,
                north_east = openapi_client.models.pathfinding_point.PathfindingPoint(
                    x = 0.0, 
                    y = 0.0, ),
                south_west = openapi_client.models.pathfinding_point.PathfindingPoint(
                    x = 0.0, 
                    y = 0.0, )
            )
        else:
            return PathfindingRequestObstacle(
                direction = 'NORTH',
                image_id = 1.0,
                north_east = openapi_client.models.pathfinding_point.PathfindingPoint(
                    x = 0.0, 
                    y = 0.0, ),
                south_west = openapi_client.models.pathfinding_point.PathfindingPoint(
                    x = 0.0, 
                    y = 0.0, ),
        )
        """

    def testPathfindingRequestObstacle(self):
        """Test PathfindingRequestObstacle"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
