# coding: utf-8

"""
    MDP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.misc_instruction import MiscInstruction

class TestMiscInstruction(unittest.TestCase):
    """MiscInstruction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMiscInstruction(self):
        """Test MiscInstruction"""
        # inst = MiscInstruction()

if __name__ == '__main__':
    unittest.main()
