# coding: utf-8

"""
    A swagger API

    powered by Flasgger

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.response_body import ResponseBody

class TestResponseBody(unittest.TestCase):
    """ResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseBody:
        """Test ResponseBody
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseBody`
        """
        model = ResponseBody()
        if include_optional:
            return ResponseBody(
                distance = 1.337,
                instructions = [
                    None
                    ]
            )
        else:
            return ResponseBody(
        )
        """

    def testResponseBody(self):
        """Test ResponseBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
