# coding: utf-8

"""
    A swagger API

    powered by Flasgger

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_pathfinding_post(self) -> None:
        """Test case for pathfinding_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
