# coding: utf-8

"""
    A swagger API

    powered by Flasgger

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.obstacle import Obstacle

class TestObstacle(unittest.TestCase):
    """Obstacle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Obstacle:
        """Test Obstacle
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Obstacle`
        """
        model = Obstacle()
        if include_optional:
            return Obstacle(
                direction = 'NORTH',
                north_east = [0, 0],
                south_west = [0, 0]
            )
        else:
            return Obstacle(
                direction = 'NORTH',
                north_east = [0, 0],
                south_west = [0, 0],
        )
        """

    def testObstacle(self):
        """Test Obstacle"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
