# coding: utf-8

"""
    MDP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.pathfinding_request_obstacle import PathfindingRequestObstacle
from openapi_client.models.pathfinding_request_robot import PathfindingRequestRobot
from typing import Optional, Set
from typing_extensions import Self

class PathfindingRequest(BaseModel):
    """
    PathfindingRequest
    """ # noqa: E501
    obstacles: Annotated[List[PathfindingRequestObstacle], Field(min_length=1)]
    robot: PathfindingRequestRobot = Field(description="The initial position of the robot.")
    verbose: Optional[StrictBool] = Field(default=True, description="Whether to attach the path and cost alongside the movement instructions in the response.")
    __properties: ClassVar[List[str]] = ["obstacles", "robot", "verbose"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PathfindingRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in obstacles (list)
        _items = []
        if self.obstacles:
            for _item in self.obstacles:
                if _item:
                    _items.append(_item.to_dict())
            _dict['obstacles'] = _items
        # override the default output from pydantic by calling `to_dict()` of robot
        if self.robot:
            _dict['robot'] = self.robot.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PathfindingRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "obstacles": [PathfindingRequestObstacle.from_dict(_item) for _item in obj["obstacles"]] if obj.get("obstacles") is not None else None,
            "robot": PathfindingRequestRobot.from_dict(obj["robot"]) if obj.get("robot") is not None else None,
            "verbose": obj.get("verbose") if obj.get("verbose") is not None else True
        })
        return _obj


